//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace FAI_lab2.Models
{
    public class Login
    {
        public int LID { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public List<int> PunetoriID { get; set; }
    

    }
}
